# https://taskfile.dev
version: '3'

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  lint:
    desc: "Run linter"
    cmds:
      - go generate ./...
      - golangci-lint run

  tests:
    desc: "Run unit tests (root module, no Docker required)"
    cmds:
      - go test ./... -v -count=2 -race

  tests-integration:
    desc: "Run integration tests (separate module, requires Docker)"
    dir: internal/integration
    cmds:
      - go test ./... -v -count=2 -race

    