package pgqueue

import (
	"crypto/rand"
	"encoding/binary"
	"fmt"
	"sync"
	"time"

	"github.com/google/uuid"
)

// UUIDv7 bit layout constants.
const (
	uuidV7Version      = 0x70 // Version 7 marker bits.
	uuidV7VersionMask  = 0x0f // Mask to clear version bits.
	uuidVariant        = 0x80 // RFC 4122 variant 10 marker bits.
	uuidVariantMask    = 0x3f // Mask to clear variant bits.
	uuidTimestampShift = 32   // Bit shift for 48-bit timestamp split.

	// uuidV7CounterMask is the 12-bit "rand_a" field used as a monotonic
	// counter (RFC 9562, method 1). It allows up to 4096 strictly-ordered
	// UUIDs per millisecond per process.
	uuidV7CounterMask = 0x0fff
	// uuidV7CounterSeedMask seeds a fresh millisecond's counter from random
	// bits while clearing the top bit, leaving headroom so a burst within the
	// same millisecond cannot overflow the 12-bit counter.
	uuidV7CounterSeedMask = 0x07ff
	// uuidV7CounterShift places the counter's high bits into byte 6.
	uuidV7CounterShift = 8
)

// uuidV7State guards the monotonic counter shared by all NewUUIDv7 callers in
// this process. UUIDv7's 48-bit timestamp only has millisecond resolution, so
// without a counter two UUIDs minted in the same millisecond would order
// randomly — breaking the "ORDER BY id" chronological guarantee that channels
// and pub/sub rely on.
var uuidV7State struct {
	mu      sync.Mutex
	lastMS  uint64
	counter uint16
}

// NewUUIDv7 generates a new UUIDv7 with time-ordered properties.
//
// The first 48 bits hold a Unix-millisecond timestamp and the following 12 bits
// hold a per-process monotonic counter, so UUIDs generated by this process are
// strictly increasing even within a single millisecond and even if the system
// clock moves backwards. The remaining 62 bits are random for global uniqueness.
//
// Monotonic-counter trade-off: when the wall clock steps backwards the
// generator keeps the previous (higher) timestamp pinned and advances only the
// counter, so freshly minted UUIDs briefly embed a timestamp slightly ahead of
// real time. As soon as the wall clock catches up — once time.Now reaches the
// pinned millisecond — the generator resyncs to real time. Monotonicity, and
// therefore "ORDER BY id" chronological ordering, is preserved throughout
// (R-20).
//
// Counter-overflow behavior: the 12-bit "rand_a" monotonic counter can hold at
// most 4096 values per millisecond. When the counter overflows (sustained
// generation exceeding ~4 million UUIDs per second), the generator re-reads the
// wall clock. If real time has moved on to a new millisecond it resyncs to that
// millisecond and reseeds the counter from random bits, so no drift occurs. Only
// when the clock has not yet advanced does the generator increment the pinned
// millisecond by one, borrowing a future millisecond to maintain strict
// monotonicity. Under a sustained burst, each overflow borrows one more
// millisecond ahead of real time. The embedded timestamp therefore loses
// high-fidelity wall-clock accuracy under extreme load; UUIDs remain strictly
// monotonic and globally unique throughout. Once the burst subsides and real
// time catches up, the generator resyncs automatically.
func NewUUIDv7() (uuid.UUID, error) {
	return newUUIDv7At(nowMillisecond)
}

// nowMillisecond returns the current Unix timestamp in milliseconds. Extracted
// so newUUIDv7At can be driven by a synthetic clock in tests.
func nowMillisecond() uint64 {
	return uint64(time.Now().UnixMilli())
}

// newUUIDv7At builds a UUIDv7 stamped from the given clock function. NewUUIDv7
// passes the wall clock; tests pass a synthetic clock to exercise the
// clock-regression resync and counter-overflow paths. The clock is called once
// at entry and again when the per-millisecond counter overflows, so the
// overflow branch can resync to real time instead of borrowing forward
// unboundedly under sustained burst load (issue #58).
func newUUIDv7At(nowFn func() uint64) (uuid.UUID, error) {
	var u uuid.UUID

	// Random fill for bytes 6-15; bytes 6-7 are overwritten with the counter
	// below, bytes 8-15 keep their randomness (minus the variant bits).
	if _, err := rand.Read(u[6:]); err != nil {
		return uuid.UUID{}, fmt.Errorf("failed to generate random bytes: %w", err)
	}

	nowMS := nowFn()

	uuidV7State.mu.Lock()
	switch {
	case nowMS > uuidV7State.lastMS:
		// The wall clock has advanced past the last pinned millisecond — a
		// normal new millisecond, or real time catching up after a backward
		// clock step. Either way, resync lastMS to the real timestamp and
		// reseed the counter from random bits (R-20).
		uuidV7State.lastMS = nowMS
		uuidV7State.counter = (uint16(u[6])<<8 | uint16(u[7])) & uuidV7CounterSeedMask
	default:
		// Same millisecond, or the clock moved backwards: keep the timestamp
		// monotonic by reusing lastMS and incrementing the counter.
		uuidV7State.counter++
		if uuidV7State.counter > uuidV7CounterMask {
			// Counter exhausted within a millisecond. Re-read the clock
			// before borrowing: if real time has moved on, resync to it
			// instead of drifting lastMS further into the future.
			nowMS = nowFn()
			if nowMS > uuidV7State.lastMS {
				uuidV7State.lastMS = nowMS
			} else {
				uuidV7State.lastMS++
			}
			uuidV7State.counter = 0
		}
	}
	ms := uuidV7State.lastMS
	counter := uuidV7State.counter
	uuidV7State.mu.Unlock()

	// Fill first 48 bits with the timestamp (6 bytes).
	binary.BigEndian.PutUint16(u[0:2], uint16(ms>>uuidTimestampShift)) //nolint:gosec // G115: timestamp fits in 48 bits.
	binary.BigEndian.PutUint32(u[2:6], uint32(ms))                     //nolint:gosec // G115: lower 32 bits of timestamp.

	// Bytes 6-7 carry the 12-bit counter (the "rand_a" field).
	u[6] = byte(counter >> uuidV7CounterShift)
	u[7] = byte(counter) //nolint:gosec // G115: low 8 bits of the 12-bit counter; truncation intended

	// Set version (7) and variant bits.
	u[6] = (u[6] & uuidV7VersionMask) | uuidV7Version
	u[8] = (u[8] & uuidVariantMask) | uuidVariant

	return u, nil
}

// ExtractTimestamp extracts the timestamp from a UUIDv7.
func ExtractTimestamp(u uuid.UUID) time.Time {
	// Extract first 48 bits as timestamp
	ms := uint64(binary.BigEndian.Uint16(u[0:2]))<<uuidTimestampShift |
		uint64(binary.BigEndian.Uint32(u[2:6]))

	return time.UnixMilli(int64(ms)) //nolint:gosec // G115: 48-bit timestamp fits in int64
}
