// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metadata.sql

package db

import (
	"context"
	"encoding/json"
)

const createQueueMetadata = `-- name: CreateQueueMetadata :one
INSERT INTO pgqueue_metadata (queue_type, queue_name, table_name, config)
VALUES ($1, $2, $3, $4)
RETURNING id, queue_type, queue_name, table_name, config, created_at, updated_at
`

type CreateQueueMetadataParams struct {
	QueueType string          `json:"queue_type"`
	QueueName string          `json:"queue_name"`
	TableName string          `json:"table_name"`
	Config    json.RawMessage `json:"config"`
}

func (q *Queries) CreateQueueMetadata(ctx context.Context, arg CreateQueueMetadataParams) (PgqueueMetadatum, error) {
	row := q.db.QueryRowContext(ctx, createQueueMetadata,
		arg.QueueType,
		arg.QueueName,
		arg.TableName,
		arg.Config,
	)
	var i PgqueueMetadatum
	err := row.Scan(
		&i.ID,
		&i.QueueType,
		&i.QueueName,
		&i.TableName,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQueueMetadata = `-- name: DeleteQueueMetadata :exec
DELETE FROM pgqueue_metadata
WHERE queue_type = $1 AND queue_name = $2
`

type DeleteQueueMetadataParams struct {
	QueueType string `json:"queue_type"`
	QueueName string `json:"queue_name"`
}

func (q *Queries) DeleteQueueMetadata(ctx context.Context, arg DeleteQueueMetadataParams) error {
	_, err := q.db.ExecContext(ctx, deleteQueueMetadata, arg.QueueType, arg.QueueName)
	return err
}

const getQueueMetadata = `-- name: GetQueueMetadata :one
SELECT id, queue_type, queue_name, table_name, config, created_at, updated_at FROM pgqueue_metadata
WHERE queue_type = $1 AND queue_name = $2
LIMIT 1
`

type GetQueueMetadataParams struct {
	QueueType string `json:"queue_type"`
	QueueName string `json:"queue_name"`
}

func (q *Queries) GetQueueMetadata(ctx context.Context, arg GetQueueMetadataParams) (PgqueueMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getQueueMetadata, arg.QueueType, arg.QueueName)
	var i PgqueueMetadatum
	err := row.Scan(
		&i.ID,
		&i.QueueType,
		&i.QueueName,
		&i.TableName,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllQueues = `-- name: ListAllQueues :many
SELECT id, queue_type, queue_name, table_name, config, created_at, updated_at FROM pgqueue_metadata
ORDER BY queue_type, queue_name
`

func (q *Queries) ListAllQueues(ctx context.Context) ([]PgqueueMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, listAllQueues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PgqueueMetadatum{}
	for rows.Next() {
		var i PgqueueMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.QueueType,
			&i.QueueName,
			&i.TableName,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueues = `-- name: ListQueues :many
SELECT id, queue_type, queue_name, table_name, config, created_at, updated_at FROM pgqueue_metadata
WHERE queue_type = $1
ORDER BY created_at DESC
`

func (q *Queries) ListQueues(ctx context.Context, queueType string) ([]PgqueueMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, listQueues, queueType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PgqueueMetadatum{}
	for rows.Next() {
		var i PgqueueMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.QueueType,
			&i.QueueName,
			&i.TableName,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQueueConfig = `-- name: UpdateQueueConfig :one
UPDATE pgqueue_metadata
SET config = $3, updated_at = NOW()
WHERE queue_type = $1 AND queue_name = $2
RETURNING id, queue_type, queue_name, table_name, config, created_at, updated_at
`

type UpdateQueueConfigParams struct {
	QueueType string          `json:"queue_type"`
	QueueName string          `json:"queue_name"`
	Config    json.RawMessage `json:"config"`
}

func (q *Queries) UpdateQueueConfig(ctx context.Context, arg UpdateQueueConfigParams) (PgqueueMetadatum, error) {
	row := q.db.QueryRowContext(ctx, updateQueueConfig, arg.QueueType, arg.QueueName, arg.Config)
	var i PgqueueMetadatum
	err := row.Scan(
		&i.ID,
		&i.QueueType,
		&i.QueueName,
		&i.TableName,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
