// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type PgqueueMetadatum struct {
	ID        uuid.UUID       `json:"id"`
	QueueType string          `json:"queue_type"`
	QueueName string          `json:"queue_name"`
	TableName string          `json:"table_name"`
	Config    json.RawMessage `json:"config"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type PgqueueReplayLog struct {
	ID           uuid.UUID       `json:"id"`
	QueueType    string          `json:"queue_type"`
	QueueName    string          `json:"queue_name"`
	ReplayType   string          `json:"replay_type"`
	ReplayParams json.RawMessage `json:"replay_params"`
	MessageCount int32           `json:"message_count"`
	CreatedAt    time.Time       `json:"created_at"`
	CreatedBy    sql.NullString  `json:"created_by"`
}

type PgqueueSubscriber struct {
	ID           uuid.UUID `json:"id"`
	TopicName    string    `json:"topic_name"`
	SubscriberID string    `json:"subscriber_id"`
	CreatedAt    time.Time `json:"created_at"`
	Active       bool      `json:"active"`
}
