// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: replay_log.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createReplayLog = `-- name: CreateReplayLog :one
INSERT INTO pgqueue_replay_log (queue_type, queue_name, replay_type, replay_params, message_count, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, queue_type, queue_name, replay_type, replay_params, message_count, created_at, created_by
`

type CreateReplayLogParams struct {
	QueueType    string          `json:"queue_type"`
	QueueName    string          `json:"queue_name"`
	ReplayType   string          `json:"replay_type"`
	ReplayParams json.RawMessage `json:"replay_params"`
	MessageCount int32           `json:"message_count"`
	CreatedBy    sql.NullString  `json:"created_by"`
}

func (q *Queries) CreateReplayLog(ctx context.Context, arg CreateReplayLogParams) (PgqueueReplayLog, error) {
	row := q.db.QueryRowContext(ctx, createReplayLog,
		arg.QueueType,
		arg.QueueName,
		arg.ReplayType,
		arg.ReplayParams,
		arg.MessageCount,
		arg.CreatedBy,
	)
	var i PgqueueReplayLog
	err := row.Scan(
		&i.ID,
		&i.QueueType,
		&i.QueueName,
		&i.ReplayType,
		&i.ReplayParams,
		&i.MessageCount,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getReplayHistory = `-- name: GetReplayHistory :many
SELECT id, queue_type, queue_name, replay_type, replay_params, message_count, created_at, created_by FROM pgqueue_replay_log
WHERE queue_type = $1 AND queue_name = $2
ORDER BY created_at DESC
LIMIT $3
`

type GetReplayHistoryParams struct {
	QueueType string `json:"queue_type"`
	QueueName string `json:"queue_name"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) GetReplayHistory(ctx context.Context, arg GetReplayHistoryParams) ([]PgqueueReplayLog, error) {
	rows, err := q.db.QueryContext(ctx, getReplayHistory, arg.QueueType, arg.QueueName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PgqueueReplayLog{}
	for rows.Next() {
		var i PgqueueReplayLog
		if err := rows.Scan(
			&i.ID,
			&i.QueueType,
			&i.QueueName,
			&i.ReplayType,
			&i.ReplayParams,
			&i.MessageCount,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReplayHistoryAll = `-- name: GetReplayHistoryAll :many
SELECT id, queue_type, queue_name, replay_type, replay_params, message_count, created_at, created_by FROM pgqueue_replay_log
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetReplayHistoryAll(ctx context.Context, limit int32) ([]PgqueueReplayLog, error) {
	rows, err := q.db.QueryContext(ctx, getReplayHistoryAll, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PgqueueReplayLog{}
	for rows.Next() {
		var i PgqueueReplayLog
		if err := rows.Scan(
			&i.ID,
			&i.QueueType,
			&i.QueueName,
			&i.ReplayType,
			&i.ReplayParams,
			&i.MessageCount,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
