// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscribers.sql

package db

import (
	"context"
)

const deleteSubscriber = `-- name: DeleteSubscriber :exec
DELETE FROM pgqueue_subscribers
WHERE topic_name = $1 AND subscriber_id = $2
`

type DeleteSubscriberParams struct {
	TopicName    string `json:"topic_name"`
	SubscriberID string `json:"subscriber_id"`
}

func (q *Queries) DeleteSubscriber(ctx context.Context, arg DeleteSubscriberParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubscriber, arg.TopicName, arg.SubscriberID)
	return err
}

const getActiveSubscribers = `-- name: GetActiveSubscribers :many
SELECT id, topic_name, subscriber_id, created_at, active FROM pgqueue_subscribers
WHERE topic_name = $1 AND active = TRUE
ORDER BY created_at
`

func (q *Queries) GetActiveSubscribers(ctx context.Context, topicName string) ([]PgqueueSubscriber, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSubscribers, topicName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PgqueueSubscriber{}
	for rows.Next() {
		var i PgqueueSubscriber
		if err := rows.Scan(
			&i.ID,
			&i.TopicName,
			&i.SubscriberID,
			&i.CreatedAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriber = `-- name: GetSubscriber :one
SELECT id, topic_name, subscriber_id, created_at, active FROM pgqueue_subscribers
WHERE topic_name = $1 AND subscriber_id = $2
LIMIT 1
`

type GetSubscriberParams struct {
	TopicName    string `json:"topic_name"`
	SubscriberID string `json:"subscriber_id"`
}

func (q *Queries) GetSubscriber(ctx context.Context, arg GetSubscriberParams) (PgqueueSubscriber, error) {
	row := q.db.QueryRowContext(ctx, getSubscriber, arg.TopicName, arg.SubscriberID)
	var i PgqueueSubscriber
	err := row.Scan(
		&i.ID,
		&i.TopicName,
		&i.SubscriberID,
		&i.CreatedAt,
		&i.Active,
	)
	return i, err
}

const registerSubscriber = `-- name: RegisterSubscriber :one
INSERT INTO pgqueue_subscribers (topic_name, subscriber_id)
VALUES ($1, $2)
ON CONFLICT (topic_name, subscriber_id)
DO UPDATE SET active = TRUE, created_at = NOW()
RETURNING id, topic_name, subscriber_id, created_at, active
`

type RegisterSubscriberParams struct {
	TopicName    string `json:"topic_name"`
	SubscriberID string `json:"subscriber_id"`
}

func (q *Queries) RegisterSubscriber(ctx context.Context, arg RegisterSubscriberParams) (PgqueueSubscriber, error) {
	row := q.db.QueryRowContext(ctx, registerSubscriber, arg.TopicName, arg.SubscriberID)
	var i PgqueueSubscriber
	err := row.Scan(
		&i.ID,
		&i.TopicName,
		&i.SubscriberID,
		&i.CreatedAt,
		&i.Active,
	)
	return i, err
}

const unregisterSubscriber = `-- name: UnregisterSubscriber :exec
UPDATE pgqueue_subscribers
SET active = FALSE
WHERE topic_name = $1 AND subscriber_id = $2
`

type UnregisterSubscriberParams struct {
	TopicName    string `json:"topic_name"`
	SubscriberID string `json:"subscriber_id"`
}

func (q *Queries) UnregisterSubscriber(ctx context.Context, arg UnregisterSubscriberParams) error {
	_, err := q.db.ExecContext(ctx, unregisterSubscriber, arg.TopicName, arg.SubscriberID)
	return err
}
